create table medicos
(
    id            bigint generated by default as identity,
    nome          varchar(100) not null,
    email         varchar(100) not null unique,
    crm           varchar(6)   not null unique,
    especialidade varchar(20)  not null,
    logradouro    varchar(100) not null,
    bairro        varchar(100) NOT NULL,
    cep           varchar(9)   not null,
    complemento   varchar(100),
    uf            char(2)      not null,
    cidade        varchar(100) not null,

    primary key (id)
);